name: Tests
on: push
jobs:
  gotests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
          export $PATH:$HOME/go/bin
          make test
